### ISSUE TITLE
Reporting and Dashboards

### ISSUE THREAD

**Issue by harshadporwal** [springernature/snics-management#126]

**Comment by karentom** [comment]
![image](https://user-images.githubusercontent.com/17595871/54637477-1a979100-4a5f-11e9-948d-2193a13be1a1.png)

**Comment by harshadporwal** [comment]
@karentom This is not a issue, this a data problem as the count for 'For Review' and 'Do not use' are very less so thats why it is not visible and the chart is configured based on the count automatically which we cannot control.

One thing Steph can do is to deselect the status from the legend which she doesnt wants to see. Please find screenshot below.

![image](https://user-images.githubusercontent.com/43807299/54662641-aca5a500-4b04-11e9-8a53-c9449068bc72.png)

**Comment by karentom** [comment]
@harshadporwal 

1.	Charts should only include latest assessments - The charts should only display the latest assessments for each partner. This includes the total counts and counts when you hover each piece of the chart.

2.	The click through should be in the same layout as the Business Partner Overview including the filter fields.
![image](https://user-images.githubusercontent.com/17595871/54711138-9f49e400-4b1f-11e9-88f0-bd8a508811fb.png)


3.	Add counts next to the statuses in the Assessment status chart. This is not needed for the other charts. This is requested because some of the statuses are so small that it doesn't appear on the chart. It appears that there are none.

![image](https://user-images.githubusercontent.com/17595871/54711214-cd2f2880-4b1f-11e9-870c-ffb6d43c74a3.png)

**Comment by harshadporwal** [comment]
@karentom  Point 1 fix is already in place. Only the latest assessment for each partner is displayed in reporting and dashboard

**Comment by harshadporwal** [comment]
@karentom Paoint 2 is a very big change. Only table display can be done quickly, but filter also needs to be working will require API changes. This changes need to be done for all charts in SNICS. Let me know your suggestion.

**Comment by harshadporwal** [comment]
@karentom Point 3 has been fixed.

![image](https://user-images.githubusercontent.com/43807299/54809346-08a92e80-4ca9-11e9-8515-cf6da7231f31.png)

**Comment by karentom** [comment]
@harshadporwal Steph is happy with these changes. This can be deployed to live.
