### ISSUE TITLE
Answered by field is incorrect

### ISSUE THREAD

**Issue by karentom** [springernature/snics-management#85]
I answered the questionnaire as an employee, but it is displaying partner.

https://github.com/springernature/snics-employee/issues/105

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51307658-44840580-1a66-11e9-8260-ccca5bc9d264.png)


Fixed and working

**Comment by karentom** [comment]
@mohammadsiddiqui @harshadporwal 

Same fix is needed on the employee side. It is correct on management side. Screenshots below are for the same assessment.

Employee portal:
![image](https://user-images.githubusercontent.com/17595871/51333885-ab94c080-1a4c-11e9-93ad-0e3433fef606.png)

Management portal:
![image](https://user-images.githubusercontent.com/17595871/51333944-ce26d980-1a4c-11e9-8941-729fb811b26e.png)

**Comment by harshadporwal** [comment]
![image](https://user-images.githubusercontent.com/43807299/51365746-ddb72880-1b07-11e9-94a4-65fcb7baa8c1.png)

@karentom  As I dont have access to partner 1007, attached screenshot for 959 partner
The fix is already there in place. Can you please try clearing the history/Incognito mode. Let us know if the issue still exist.

**Comment by karentom** [comment]
Tested and works.
